#!/usr/bin/perl
# $latex         = 'uplatex %O -shell-escape -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1 -kanji=utf8 -pv %S';
# -synctex: pdf と tex の相互ジャンプ
# -shell-escape: 任意の外部プログラムを TeX から実行できるように
    # 例えば画像読み込み時とかに外部コマンドが必要
# -file-line-erro: エラーメッセージにファイル名と行番号を追加
# -halt-on-error: stop processing at the first error
# -interaction=nonstopmode: tells the TeX engine to run with minimal interaction with the user and as far as possible to 'go past' errors
# -halt-on-error -interaction=nonstopmode: interaction=nonstopmode が 止まるぐらいの最初のエラーで停止
# $bibtex        = 'upbibtex %O %B -kanji=utf8';
# $dvipdf        = 'dvipdfmx %O -o %D %S';
# $pdf_mode      = 3; # use dvipdfmx


# $latex = 'uplatex %O -synctex=1 -interaction=nonstopmode %S';
# $pdflatex = 'pdflatex %O -synctex=1 -interaction=nonstopmode %S';
# $lualatex = 'lualatex %O -synctex=1 -interaction=nonstopmode %S';
$lualatex  = 'lualatex %O -synctex=1 -file-line-error -halt-on-error %S';
# $xelatex = 'xelatex %O -synctex=1 -interaction=nonstopmode %S';
# $biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B';
$bibtex = 'upbibtex %O %B';
# $makeindex = 'upmendex %O -o %D %S';
# $dvipdf = 'dvipdfmx %O -o %D %S';
# $dvips = 'dvips %O -z -f %S | convbkmk -u > %D';
# $ps2pdf = 'ps2pdf %O %S %D';
$pdf_mode = 4;
$pvc_view_file_via_temporary = 0;
$pdf_previewer = 'open -ga /Applications/Skim.app';